# on: 
#   push:
#     branches:
#       - 'main'
#     paths:
#       - 'website_material/**'
name: Copy Files
on: 
  issues:
    types: 
      - labeled
      
jobs:
  update-doi:
    if: contains(github.event.label.name, 'published')
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.update_doi.outputs.success }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: pip install -r .github/scripts/requirements.txt

      - name: update doi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_NAME: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          SUCCESS=$(python3 .github/scripts/update_doi.py)
          echo "success=${SUCCESS}" >> $GITHUB_OUTPUT

  copy-files:
    needs: update-doi
    if: ${{ needs.update-doi.outputs.success == 'True' }}
    runs-on: ubuntu-latest
    steps:  
      - name: create token for website repo
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: 'website'

      - name: copy files to website repo
        uses: lubu12/copy-files-to-repository@v1
        env:
          API_TOKEN_GITHUB: ${{ steps.app-token.outputs.token }}
        with:
          source-files: 'website_material/'
          destination-username: ${{ github.repository_owner }}
          destination-repository: 'website'
          destination-branch: ${{ github.repository.name }}
          destination-directory: 'src/pages/models/${{ github.repository.name }}'
          commit-email: 'sara.moronpolanco@sydney.edu.au'