# on: 
#   push:
#     branches:
#       - 'main'
#     paths:
#       - 'website_material/**'
name: Copy Files
on: 
  issues:
    types: 
      - labeled
      
jobs:
  copy-files:
    if: contains(github.event.label.name, 'published')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: 'website'

      - uses: lubu12/copy-files-to-repository@v1
        env:
          API_TOKEN_GITHUB: ${{ steps.app-token.outputs.token }}
        with:
          source-files: 'website_material/'
          destination-username: ${{ github.repository_owner }}
          destination-repository: 'website'
          destination-branch: ${{ github.repository.name }}
          destination-directory: 'src/pages/models/${{ github.repository.name }}'
          commit-email: ''